theme = "dark_plus"

[keys.normal]
C-q = ":quit"
# C-s = [":write"]
C-e = "command_mode"
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-down = "goto_next_buffer"
S-up = "goto_previous_buffer"
